version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: code-system-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: code_system
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - code-system-network

  app:
    build: .
    container_name: code-system-app
    ports:
      - "${APP_PORT:-8080}:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: code_system
    networks:
      - code-system-network

volumes:
  postgres_data:

networks:
  code-system-network:
    driver: bridge